version: '3.8'

services:
  wuiam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./logs:/app/logs
    container_name: wuiam-app
