version: '3.8'

services:
  wuiam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=10.255.255.43,1433;Database=WUIAMDb;User=sa;Password=WU-2025,dfh;TrustServerCertificate=True;Encrypt=False;"
    restart: always
    volumes:
      - ./logs:/app/logs
    container_name: wuiam-app